#!/usr/bin/env bash
# ============================================================================
# setup_polygon_cron.sh — Install cron jobs for Polygon data updates + scans
# ============================================================================
#
# Installs two cron entries:
#   1. Daily Polygon data update (22:00 UTC / 6 PM ET, Mon-Fri)
#   2. Scanner runs for paper trading experiments (14 scans/day, market hours)
#
# Usage:
#   ./scripts/setup_polygon_cron.sh              # install all cron entries
#   ./scripts/setup_polygon_cron.sh --status     # show current cron state
#   ./scripts/setup_polygon_cron.sh --remove     # remove all pilotai cron entries
#
# Prerequisites:
#   - .env file with POLYGON_API_KEY
#   - Alpaca env files (.env.exp400, .env.exp401, etc.) for scanner
#   - Python 3 with required packages
#
# ============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

MARKER="# pilotai-credit-spreads"
DATA_UPDATE="$SCRIPT_DIR/daily_data_update.sh"
SCAN_SCRIPT="$SCRIPT_DIR/scan-cron-portable.sh"
DATA_LOG="$PROJECT_DIR/data/daily_update_cron.log"
SCAN_LOG="$PROJECT_DIR/logs/scan-cron.log"

ACTION="${1:-install}"

_check_prereqs() {
    local ok=true

    if [ ! -x "$DATA_UPDATE" ]; then
        echo "WARN: $DATA_UPDATE not executable (run: chmod +x $DATA_UPDATE)"
        ok=false
    fi

    if [ ! -f "$PROJECT_DIR/.env" ]; then
        echo "WARN: $PROJECT_DIR/.env not found — data update needs POLYGON_API_KEY"
    fi

    for envf in .env.exp400 .env.exp401; do
        if [ ! -f "$PROJECT_DIR/$envf" ]; then
            echo "WARN: $PROJECT_DIR/$envf not found — scanner for ${envf/.env./} will fail"
        fi
    done

    if ! command -v python3 &>/dev/null; then
        echo "ERROR: python3 not found"
        ok=false
    fi

    $ok
}

_generate_portable_scan() {
    # Create a portable version of scan-cron.sh that auto-detects paths
    cat > "$SCAN_SCRIPT" << 'SCANEOF'
#!/usr/bin/env bash
# scan-cron-portable.sh — Portable scanner cron for all paper experiments
# Auto-generated by setup_polygon_cron.sh — do not edit manually.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
LOG_DIR="$PROJECT_DIR/logs"
MAX_LOG_SIZE=$((5 * 1024 * 1024))

mkdir -p "$LOG_DIR"

# Skip weekends
DOW=$(TZ=America/New_York date +%u 2>/dev/null || date +%u)
if [ "$DOW" -gt 5 ]; then
    exit 0
fi

cd "$PROJECT_DIR"

_run_scan() {
    local EXP="$1" CONFIG="$2" ENV_FILE="$3" DB="$4"
    local LOG_FILE="$LOG_DIR/scan-cron-${EXP}.log"

    # Skip if env file missing
    if [ ! -f "$ENV_FILE" ]; then
        echo "[$(date -u +%Y-%m-%dT%H:%M:%SZ)] SKIP $EXP — $ENV_FILE not found" >> "$LOG_FILE"
        return
    fi

    # Create DB directory if needed
    mkdir -p "$(dirname "$DB")"

    # Rotate log if too large
    if [ -f "$LOG_FILE" ]; then
        local sz
        sz=$(wc -c < "$LOG_FILE" 2>/dev/null || echo 0)
        if [ "$sz" -gt "$MAX_LOG_SIZE" ]; then
            mv "$LOG_FILE" "${LOG_FILE}.1"
        fi
    fi

    echo "[$(date -u +%Y-%m-%dT%H:%M:%SZ)] Starting $EXP scan" >> "$LOG_FILE"
    python3 main.py scan \
        --config "$CONFIG" \
        --env-file "$ENV_FILE" \
        --db "$DB" \
        >> "$LOG_FILE" 2>&1 || \
    echo "[$(date -u +%Y-%m-%dT%H:%M:%SZ)] $EXP scan failed ($?)" >> "$LOG_FILE"
    echo "---" >> "$LOG_FILE"
}

_run_scan "exp400" "configs/paper_champion.yaml" ".env.exp400" "data/pilotai_exp400.db"
_run_scan "exp401" "configs/paper_exp401.yaml"   ".env.exp401" "data/pilotai_exp401.db"
_run_scan "exp503" "configs/paper_exp503.yaml"   ".env.exp503" "data/exp503/pilotai_exp503.db"
_run_scan "exp600" "configs/paper_exp600.yaml"   ".env.exp600" "data/exp600/pilotai_exp600.db"
SCANEOF
    chmod +x "$SCAN_SCRIPT"
    echo "Generated portable scan script: $SCAN_SCRIPT"
}

case "$ACTION" in
    --status|-s)
        echo "=== Cron Status ==="
        echo
        echo "PilotAI cron entries:"
        crontab -l 2>/dev/null | grep -A1 "pilotai" || echo "  (none installed)"
        echo
        echo "Full crontab:"
        crontab -l 2>/dev/null || echo "  (no crontab)"
        echo
        echo "=== Prerequisites ==="
        _check_prereqs || true
        echo
        echo "=== Data Files ==="
        echo "options_cache.db: $(ls -lh "$PROJECT_DIR/data/options_cache.db" 2>/dev/null | awk '{print $5, $6, $7, $8}' || echo 'NOT FOUND')"
        echo "pilotai.db:       $(ls -lh "$PROJECT_DIR/data/pilotai.db" 2>/dev/null | awk '{print $5, $6, $7, $8}' || echo 'NOT FOUND')"
        echo "pilotai_exp401.db:$(ls -lh "$PROJECT_DIR/data/pilotai_exp401.db" 2>/dev/null | awk '{print $5, $6, $7, $8}' || echo 'NOT FOUND')"
        echo "EXP-503 DB:       $(ls -lh "$PROJECT_DIR/data/exp503/pilotai_exp503.db" 2>/dev/null | awk '{print $5, $6, $7, $8}' || echo 'NOT FOUND')"
        echo "EXP-600 DB:       $(ls -lh "$PROJECT_DIR/data/exp600/pilotai_exp600.db" 2>/dev/null | awk '{print $5, $6, $7, $8}' || echo 'NOT FOUND')"
        ;;

    --remove|-r)
        if crontab -l 2>/dev/null | grep -q "pilotai"; then
            crontab -l 2>/dev/null | grep -v "pilotai" | grep -v "daily_data_update" | grep -v "scan-cron" | crontab -
            echo "Removed all pilotai cron entries."
        else
            echo "No pilotai cron entries found."
        fi
        ;;

    install|--install|-i|"")
        echo "=== Installing PilotAI Cron Jobs ==="
        echo

        # Check prerequisites
        _check_prereqs || echo "(continuing with warnings)"

        # Generate portable scan script
        _generate_portable_scan

        # Ensure scripts are executable
        chmod +x "$DATA_UPDATE" 2>/dev/null || true
        chmod +x "$SCAN_SCRIPT" 2>/dev/null || true

        # Create log directories
        mkdir -p "$PROJECT_DIR/data" "$PROJECT_DIR/logs"
        mkdir -p "$PROJECT_DIR/data/exp503" "$PROJECT_DIR/data/exp600"

        # Remove existing pilotai entries
        if crontab -l 2>/dev/null | grep -q "pilotai"; then
            crontab -l 2>/dev/null | grep -v "pilotai" | grep -v "daily_data_update" | grep -v "scan-cron" | crontab -
        fi

        # Install cron entries
        # Schedule:
        #   22:00 UTC Mon-Fri: Daily Polygon data update (6 PM ET)
        #   14:30-20:00 UTC Mon-Fri: Scanner runs every 30 min during market hours
        #     (9:30 AM - 4:00 PM ET = 14:30 - 21:00 UTC)
        (
            crontab -l 2>/dev/null || true
            echo ""
            echo "$MARKER — daily Polygon data update (22:00 UTC = 6 PM ET)"
            echo "0 22 * * 1-5 $DATA_UPDATE >> $DATA_LOG 2>&1"
            echo "$MARKER — scanner runs every 30 min during market hours"
            echo "*/30 14-20 * * 1-5 $SCAN_SCRIPT >> $SCAN_LOG 2>&1"
        ) | crontab -

        echo "Cron entries installed:"
        echo
        echo "  1. Daily data update"
        echo "     Schedule: 22:00 UTC Mon-Fri (6 PM ET)"
        echo "     Command:  $DATA_UPDATE"
        echo "     Log:      $DATA_LOG"
        echo
        echo "  2. Paper trading scanner"
        echo "     Schedule: Every 30 min, 14:30-20:30 UTC Mon-Fri (market hours)"
        echo "     Command:  $SCAN_SCRIPT"
        echo "     Log:      $SCAN_LOG"
        echo
        echo "Verify:    $0 --status"
        echo "Remove:    $0 --remove"
        echo "Test data: $DATA_UPDATE --dry-run"
        echo "Test scan: $SCAN_SCRIPT"
        ;;

    *)
        echo "Usage: $0 [install|--status|--remove]"
        exit 1
        ;;
esac
